// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-q2A1_uC6gegyJctBhg9ynahYAIMty0',
    appId: '1:753514115441:web:5ae6040b881a0d3da986d0',
    messagingSenderId: '753514115441',
    projectId: 'clone-fcc-2024',
    authDomain: 'clone-fcc-2024.firebaseapp.com',
    storageBucket: 'clone-fcc-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMyGIwgM5NfokSDkZI8NX2ouQfvxe0DE',
    appId: '1:753514115441:android:9f5148cfbf1889bca986d0',
    messagingSenderId: '753514115441',
    projectId: 'clone-fcc-2024',
    storageBucket: 'clone-fcc-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF414ILee0oTMq_XVefFoq0fLtS0jynQ4',
    appId: '1:753514115441:ios:67f71dcd7bade858a986d0',
    messagingSenderId: '753514115441',
    projectId: 'clone-fcc-2024',
    storageBucket: 'clone-fcc-2024.appspot.com',
    iosBundleId: 'com.example.youtubeCloneFcc2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF414ILee0oTMq_XVefFoq0fLtS0jynQ4',
    appId: '1:753514115441:ios:67f71dcd7bade858a986d0',
    messagingSenderId: '753514115441',
    projectId: 'clone-fcc-2024',
    storageBucket: 'clone-fcc-2024.appspot.com',
    iosBundleId: 'com.example.youtubeCloneFcc2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs-q2A1_uC6gegyJctBhg9ynahYAIMty0',
    appId: '1:753514115441:web:308ca42232af6abda986d0',
    messagingSenderId: '753514115441',
    projectId: 'clone-fcc-2024',
    authDomain: 'clone-fcc-2024.firebaseapp.com',
    storageBucket: 'clone-fcc-2024.appspot.com',
  );
}
